---
- name: packages | install packages for Suse
  package:
    name:
      - glibc-32bit
      - glibc-i18ndata
      - glibc-locale-32bit
      - libgcc_s1-32bit
      - libidn11-32bit
      - libX11-6-32bit
      - libcurl4-32bit
      - libz1-32bit
      - libuuid1-32bit
    state: present
  when: ansible_os_family == 'Suse'