- name: main | listener for dbload on both servers
  import_tasks: dbload_both.yml
  when: dbload_approach == 'both'

- name: main | listener for dbload on primary servers
  import_tasks: dbload_primary.yml
  when: dbload_approach == 'primary'