---

- name: restart sssd service
  systemd:
    state: restarted
    daemon_reload: yes
    name: sssd
  become: yes
  listen: restart-sssd

- name: Restart network
  service:
    name: NetworkManager
    state: restarted
  become: yes
  listen: restart-network
