- name: download | download softwares 
  command: azcopy cp '{{ item.url }}{{ item.token }}' {{ item.dest }} --recursive=true --overwrite=ifSourceNewer
  args:
    chdir: "{{ root_dir }}"
  with_items:
    - "{{ downloads }}"
  tags:
    - download