- name: Ensure volume groups exist
  lvg:
    pvs: "{{ item.pvs }}"
    vg: "{{ item.vg | default(item.ref) }}"
    state: present
  loop: "{{ volume_groups }}"

- name: Ensure logical volumes exist
  lvol:
    vg: "{{ item.vg | default(item.ref) }}"
    lv: "{{ item.lv | default(item.ref) }}"
    size: "{{ item.size | default('100%VG') }}"
    opts: -i "{{ item.stripes | default(1) }}" -I "{{ item.stripe_size | default(64) }}"
    active: yes
    shrink: "{{ item.shrink | default('yes') }}"
    state: present
  loop: "{{ volume_groups }}"

- name: main | Ensure base filesystems for logical volumes exist
  filesystem:
    fstype: "{{ item.fstype | default('xfs') }}"
    dev: "/dev/mapper/{{ item.vg | default(item.ref) }}-{{ item.lv | default(item.ref) }}"
    force: no
  when: item.mount is defined
  loop: "{{ volume_groups }}"

- name: main | Ensure directories for mounted file systems exist
  file:
    path: "{{ item.mount }}"
    state: directory
    mode: "{{ item.mode | default('0755') }}"
  when: item.mount is defined
  loop: "{{ volume_groups }}"

- name: main | Ensure filesystems are mounted to the required directories
  mount:
    path: "{{ item.mount }}"
    src: "/dev/mapper/{{ item.vg | default(item.ref) }}-{{ item.lv | default(item.ref) }}"
    fstype: "{{ item.fstype | default('xfs') }}"
    opts: "{{ item.opts | default ('defaults') }}"
    state: mounted
  when: item.mount is defined
  loop: "{{ volume_groups }}"