######################################################################
#                       DB CHECKS                                 #
######################################################################

- name: main | db-checks
  block: 
    - name: Checking HDB version
      shell : "sudo su - {{dbsid|lower}}adm -c 'HDB version' | grep version |sed -n 2p| awk '{print $2}'"
      become: yes
      register: output_hanaversionaz
      ignore_errors: true
      when: platform is not defined

    - name: Checking HDB version
      shell : "sudo su - {{dbsid|lower}}adm 'HDB version' | grep version |sed -n 2p| awk '{print $2}'"
      become: yes
      register: output_hanaversionot
      ignore_errors: true
      when: platform is defined

    - name: Checking HDB User Store
      shell : "sudo su - {{dbsid|lower}}adm  -c 'hdbuserstore list'"
      become: yes
      register: output_hdbsuserstore
      ignore_errors: true

    - name: Checking if auto NUMA balancing is disbaled
      shell: cat /etc/default/grub | grep -oP '(?<=numa_balancing=)\w+'
      become: yes
      register: output_numabal
      ignore_errors: true
      
    - debug:
        var: output_numabal
  when: "'db' in group_names"

- debug:
     var: output_hanaversionaz 

- debug:
     var: output_hdbsuserstore 

- debug:
     msg: "{{ output_hdbsuserstore | to_json }}" 

- debug:
    var: output_numabal

- name: DB checks
  template:
    src: "db-checks-md.j2"
    dest: ../md-collection/{{ ansible_date_time.iso8601_micro }}_db-checks-md.md
  delegate_to: localhost  
  when: 
    - output == "md"  
    - "'db' in group_names"
