node1: "{{ groups['std'][0] }}"
swapfile_size: 640000000 #65536
tune: "{{ sap.tune }}"
product_id: "{{ sap.product_ids.std }}"


users:
  bin:
    uid: 1010
  bingroup:
    gid: 82
  sidadm:
    uid: 1003
  dbsidadm:
    uid: 1012
  sapinst:
    gid: 1101
  sapsys:
    gid: 1100
  db2sid:
    uid: 1014
  sapsid:
    uid: 1016
  dbsidadmgroup:
    gid: 1120
  dbsidctl:
    gid: 1121
  dbsidmon:
    gid: 1122
  dbsidmnt:
    gid: 1123

groupsetup:
  - name: sapsys
    gid: "{{ users.sapsys.gid }}"
  - name: sapinst
    gid: "{{ users.sapinst.gid }}"
  - name: bin
    gid: "{{ users.bingroup.gid }}"  
  - name: "db{{ sap.db.sid|lower }}adm"
    gid: "{{ users.dbsidadmgroup.gid }}" 
  - name: "db{{ sap.db.sid|lower }}ctl"
    gid: "{{ users.dbsidctl.gid }}" 
  - name: "db{{ sap.db.sid|lower }}mon"
    gid: "{{ users.dbsidmon.gid }}" 
  - name: "db{{ sap.db.sid|lower }}mnt"
    gid: "{{ users.dbsidmnt.gid }}" 
  
usersetup:
  - name: bin
    uid: "{{ users.bin.uid }}"
    group: bin
    shell: /bin/sh
    password: "{{ vault_passwords.sidadm }}"
    sudo: true
  - name: "{{ sap.sid|lower }}adm"
    uid: "{{ users.sidadm.uid }}"
    group: sapsys
    shell: /bin/csh
    password: "{{ vault_passwords.sidadm }}"  
    sudo: true
  - name: "db2{{ sap.db.sid|lower }}"
    uid: "{{ users.db2sid.uid }}"
    group: "db{{ sap.db.sid|lower }}adm"
    groups: sapinst
    home: /db2/db2{{ sap.db.sid|lower }}
    shell: /bin/csh
    password: "{{ vault_passwords.sidadm }}"  
    sudo: true
  - name: "sap{{ sap.sid|lower }}"    
    uid: "{{ users.sapsid.uid }}"
    group: "db{{ sap.db.sid|lower }}mon"
    shell: /bin/csh
    password: "{{ vault_passwords.sidadm }}"  
    sudo: true

volume_groups:  
  # - ref: sapdata
  #   pvs: /dev/disk/azure/data/by-lun/4
  #   vg: VGDATA
  #   lv: lv_db2DX1data1
  #   mount: /db2/DX1/sapdata1
  # - ref: db2log-log_dir
  #   pvs: /dev/disk/azure/data/by-lun/5
  #   vg: VGLOG
  #   lv: lv_db2DX1log
  #   size: 14g
  #   mount: /db2/DX1/log_dir
  # - ref: db2log-saptmp1
  #   pvs: /dev/disk/azure/data/by-lun/5
  #   vg: VGLOG
  #   lv: lv_db2DX1tmp
  #   size: 20g
  #   mount: /db2/DX1/saptmp1
  # - ref: db2archive-archive
  #   pvs: /dev/disk/azure/data/by-lun/6
  #   vg: VGARCH
  #   lv: lv_db2DX1archive
  #   size: 20g
  #   mount: /db2/DX1/log_archive
  # - ref: db2archive-retrieve
  #   pvs: /dev/disk/azure/data/by-lun/6
  #   vg: VGARCH
  #   lv: lv_db2DX1retrieve
  #   size: 10g
  #   mount: /db2/DX1/log_retrieve
  # - ref: usrsaptrans
  #   pvs: /dev/disk/azure/data/by-lun/2
  #   vg: VGTRANS
  #   lv: lv_trans
  #   size: 25g
  #   mount: /usr/sap/trans
  # - ref: usrsap-usrsap
  #   pvs: /dev/disk/azure/data/by-lun/1
  #   vg: VGSAP
  #   lv: lv_usrsap
  #   size: 79g
  #   mount: /usr/sap
  # - ref: usrsap-sapmnt
  #   pvs: /dev/disk/azure/data/by-lun/1
  #   vg: VGSAP
  #   lv: lv_sapmnt
  #   size: 20g
  #   mount: /sapmnt
  # - ref: db2-dx1
  #   pvs: /dev/disk/azure/data/by-lun/3
  #   vg: VGDB2BIN
  #   lv: lv_db2DX1
  #   size: 10g
  #   mount: /db2/DX1
  # - ref: db2-dx1dump
  #   pvs: /dev/disk/azure/data/by-lun/3
  #   vg: VGDB2BIN
  #   lv: lv_db2DX1dump
  #   size: 10g
  #   mount: /db2/DX1/db2_dump
  # - ref: db2-db2dx1
  #   pvs: /dev/disk/azure/data/by-lun/3
  #   vg: VGDB2BIN
  #   lv: lv_db2DX1inst
  #   size: 10g
  #   mount: /db2/db2dx1
  # - ref: db2-ilmt
  #   pvs: /dev/disk/azure/data/by-lun/3
  #   vg: VGDB2BIN
  #   lv: lv_ilmt
  #   size: 1g
  #   mount: /ilmt
  # - ref: opttraps
  #   pvs: /dev/disk/azure/data/by-lun/7
  #   vg: VG_CORTEX
  #   lv: lv_cortex
  #   size: 10g
  #   mount: /opt/traps
  # - ref: dbexport
  #   pvs: /dev/disk/azure/data/by-lun/8
  #   vg: VGEXP
  #   lv: lv_export
  #   size: 160g
  #   mount: /export
  - ref: db2backup
    pvs: /dev/disk/azure/data/by-lun/9
    vg: VGDB2BACKUP
    lv: lv_db2backup
    size: 511g
    mount: /db2backup