---
- name: rhel | Set FireWall for azure and rhel
  import_tasks: firewall.yml
  tags:
    - firewall

- name: Start PCS Service
  command: "{{ item }}"
  with_items: 
    - systemctl start pcsd.service
    - systemctl enable pcsd.service

- name: rhel | setup ssh keys for azure and rhel
  import_tasks: ssh_key_setup.yml
  tags:
    - ssh

- name: rhel | run base ha cluster commands for azure and rhel
  import_tasks: rhel_ha_cluster.yml
  tags:
    - rhel_ha_cluster
  
- name: rhel | stonith configuration for azure and rhel
  import_tasks: azure_stonith.yml
  tags:
    - azure_stonith