---
- name: Vinci Create Linux User
  remote_user: root
  become: true
  hosts: 
    - 10.130.65.6
    - 10.130.65.4
    - 10.130.65.8
  vars_files:
    - vault.yml
  
  tasks:

    - name: Ensure ansb_admin user exists
      user:
        name: ansb_admin
        comment: "Ansible Admin User"
        shell: /bin/bash
        password: "{{ vault_password | password_hash('sha512') }}"
        create_home: yes

    - name: Add ansb_admin to sudoers
      copy:
        dest: /etc/sudoers.d/ansb_admin
        content: |
          ansb_admin ALL=(ALL) NOPASSWD: ALL
        mode: '0440'


