- name: grub | copy in grub file
  vars:
    files:
      - grub.{{ ansible_os_family }}_{{ ansible_distribution_version }}
      - grub.{{ ansible_os_family }}_{{ ansible_distribution_major_version }}
  copy:
    src: "{{ lookup('first_found', files) }}"
    dest: /etc/default/grub
  register: hanarules

- name: grub | tweak sysctl entries
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - { name: net.core.wmem_max, value: 16777216 }
    - { name: net.core.rmem_max, value: 16777216 }
    - { name: net.ipv4.tcp_wmem, value: 65536 16777216 16777216 }
    - { name: net.ipv4.tcp_rmem, value: 65536 16777216 16777216 }
    - { name: net.ipv4.tcp_timestamps, value: 1 }
    - { name: net.ipv4.tcp_syncookies, value: 1 }
    - { name: net.ipv4.conf.default.secure_redirects, value: 0 }
    - { name: net.ipv4.conf.all.secure_redirects, value: 0 }
    - { name: net.ipv4.tcp_slow_start_after_idle, value: 0 }
    - { name: net.core.somaxconn, value: 4096 }
    - { name: net.ipv4.tcp_max_syn_backlog, value: 8192 }
    - { name: net.ipv4.tcp_syn_retries, value: 8 }

- name: grub | grub2-mkconfig
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
  when: hanarules.changed

- name: reboot server
  reboot:
  when: hanarules.changed
