- name: "Ensure mounting of cramfs filesystems is disabled"
  lineinfile:
    dest: /etc/modprobe.d/CIS.conf
    regexp: "^(#)?install cramfs(\\s|$)"
    line: "install cramfs /bin/true"
    create: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - cramfs

- name: "Ensure mounting of freevxfs filesystems is disabled"
  lineinfile:
    dest: /etc/modprobe.d/CIS.conf
    regexp: "^(#)?install freevxfs(\\s|$)"
    line: "install freevxfs /bin/true"
    create: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - freevxfs

- name: "Ensure mounting of jffs2 filesystems is disabled"
  lineinfile:
    dest: /etc/modprobe.d/CIS.conf
    regexp: "^(#)?install jffs2(\\s|$)"
    line: "install jffs2 /bin/true"
    create: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - jffs2

- name: "Ensure mounting of hfs filesystems is disabled"
  lineinfile:
    dest: /etc/modprobe.d/CIS.conf
    regexp: "^(#)?install hfs(\\s|$)"
    line: "install hfs /bin/true"
    create: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - hfs

- name: "Ensure mounting of hfsplus filesystems is disabled"
  lineinfile:
    dest: /etc/modprobe.d/CIS.conf
    regexp: "^(#)?install hfsplus(\\s|$)"
    line: "install hfsplus /bin/true"
    create: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - hfsplus

- name: "Ensure mounting of squashfs filesystems is disabled"
  lineinfile:
    dest: /etc/modprobe.d/CIS.conf
    regexp: "^(#)?install squashfs(\\s|$)"
    line: "install squashfs /bin/true"
    create: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - squashfs

- name: "Ensure mounting of udf filesystems is disabled"
  lineinfile:
    dest: /etc/modprobe.d/CIS.conf
    regexp: "^(#)?install udf(\\s|$)"
    line: "install udf /bin/true"
    create: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - udf

- name: "Ensure mounting of FAT filesystems is disabled"
  lineinfile:
    dest: /etc/modprobe.d/CIS.conf
    regexp: "^(#)?install vfat(\\s|$)"
    line: "install vfat /bin/true"
    create: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - vfat

- name: "Ensure sticky bit is set on all world-writable directories"
  shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d -perm -0002 2>/dev/null | xargs chmod a+t
  #when: sticky_bit_on_worldwritable_dirs_audit.rc == '0'
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    
- name: "Ensure package manager repositories are configured"
  command: dnf repolist
  changed_when: false
  failed_when: false
  args:
    warn: false
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    
- name: "Ensure AIDE is installed"
  yum:
    name: aide
    state: present
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
   
- name: "Ensure AIDE is installed"
  command: /usr/sbin/aide --init -B 'database_out=file:/var/lib/aide/aide.db.gz'
  args:
    creates: /var/lib/aide/aide.db.gz
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
    - rhel7cis_config_aide is defined and rhel7cis_config_aide
  async: 45
  poll: 0
  tags:
    - level1
    - aide

- name: "Ensure permissions on bootloader config are configured"
  stat:
    path: /etc/grub2.cfg
  register: grub_cfg
  tags:
    - level1
    
- name: "Ensure permissions on bootloader config are configured"
  file:
    path: "{{ grub_cfg.stat.lnk_source }}"
    owner: root
    group: root
    mode: 0600
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
    - grub_cfg is defined and grub_cfg.stat.exists and grub_cfg.stat.islnk
  tags:
    - level1
    - grub
    
- name: "Ensure core dumps are restricted"
  lineinfile:
    state: present
    dest: /etc/security/limits.conf
    regexp: '^#?\\*.*core'
    line: '*                hard    core            0'
    insertbefore: '^# End of file'
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    
- name: "Ensure core dumps are restricted"
  sysctl:
    name: fs.suid_dumpable
    value: 0
    state: present
    reload: yes
    sysctl_set: yes
    ignoreerrors: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - sysctl
   
- name: "Ensure address space layout randomization (ASLR) is enabled"
  sysctl:
    name: kernel.randomize_va_space
    value: 2
    state: present
    reload: yes
    sysctl_set: yes
    ignoreerrors: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1

- name: "Ensure SELinux is installed"
  yum:
    name: libselinux
    state: present
  when:
    - rhel7cis_level2 is defined and rhel7cis_level2
  tags:
    - level2

# - name: "Ensure SELinux is installed"
#   yum:
#     name: policycoreutils-python
#     state: present
#   when:
#     - rhel7cis_level2 is defined and rhel7cis_level2
#   tags:
#     - level2

- name: "Ensure SELinux is not disabled in bootloader configuration"
  replace:
    dest: /etc/default/grub
    regexp: '(selinux|enforcing)\s*=\s*0\s*'
#    follow: true
  register: selinux_grub_patch
  ignore_errors: yes
  # notify: generate new grub config
  when:
    - rhel7cis_level2 is defined and rhel7cis_level2
  tags:
    - level2
    - scored
    - patch
    - rule_1.6.1.1

- name: "Ensure the SELinux state is enforcing"
  selinux:
    conf: /etc/selinux/config
    policy: "{{ rhel7cis_selinux_pol }}"
    state: enforcing
  when:
    - rhel7cis_level2 is defined and rhel7cis_level2
    - rhel7cis_selinux_disable is defined and not rhel7cis_selinux_disable
  tags:
    - level2
    
- name: "Ensure SELinux policy is configured"
  selinux:
    conf: /etc/selinux/config
    policy: "{{ rhel7cis_selinux_pol }}"
    state: enforcing
  when:
    - rhel7cis_level2 is defined and rhel7cis_level2
    - rhel7cis_selinux_disable is defined and not rhel7cis_selinux_disable
  tags:
    - level2
    - selinux
    

- name: "Ensure the MCS Translation Service (mcstrans) is not installed"
  yum:
    name: mcstrans
    state: absent
  when:
    - rhel7cis_level2 is defined and rhel7cis_level2
  tags:
    - level2
    
# - name: "Ensure local login warning banner is configured properly"
#   template:
#     src: etc/issue.j2
#     dest: /etc/issue
#   when:
#     - rhel7cis_level1 is defined and rhel7cis_level1
#   tags:
#     - level1
    
- name: "Ensure updates, patches, and additional security software are installed"
  yum:
    name: "*"
    state: latest
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
    - rhel7cis_update is defined and rhel7cis_update
  tags:
    - level1
    
