---

- name: create local sql accounts
  win_user:
    name: "{{ item.value.username }}"
    password: "{{ item.value.password }}"
    state: present
    groups: "{{ item.value.groups }}"
  with_dict: "{{ mssql_params.service_accounts.users }}"
  when: mssql_params.service_accounts.type == "local"

- name: create domain sql accounts
  win_domain_user:
    name: "{{ item.value.name }}"
    password: "{{ item.value.password }}"
    password_never_expires: yes
    upn: "{{ item.value.username }}@{{ domain_fqdn }}"
    state: present
    domain_username: "{{ ansible_user }}"
    domain_password: "{{ ansible_password }}"
    domain_server: "{{ domain_controller }}"
  delegate_to: "{{ domain_controller }}"
  with_dict: "{{ mssql_params.service_accounts.users }}"
  when: mssql_params.service_accounts.type == "domain"