---

- name: define /etc/chrony.conf
  template:
    src: chrony.j2
    dest: /etc/chrony.conf
  register: chrony_conf
  become: yes

- name: start and enable chrony service
  service:
    name: chronyd
    state: started
    enabled: yes
  become: yes

- name: restart chrony service now if chrony.conf file was updated
  service:
    name: chronyd
    state: restarted
  become: yes
  when:
    - chrony_conf is changed

- name: get chrony sources
  command: /usr/bin/chronyc sourcestats
  register: chrony_stats

- name: debug chrony_stats
  debug:
    var: chrony_stats
    verbosity: "{{ verbosity_level }}"

# TODO: add some validation