- name: configuration prereqs
  command: su - db2{{ sap.db.sid|lower }} -c "db2start"
  register: db2start
  failed_when:
    - db2start.failed
    - not (db2start.stderr.find("The database manager is already active.")) 

- name: configuration prereqs
  command: su - db2{{ sap.db.sid|lower }} -c "db2stop force"

- name: configuration prereqs
  command: "{{ item }}"
  with_items: 
    - sudo usermod -s /bin/ksh "db2{{ sap.db.sid|lower }}"