---
# - name: run configuration prereqs for suse db2
#   import_tasks: db2_config_prereqs.yml
#   when: cluster_type == 'db2'

- name: redhat cluster primitives
  include_tasks: "{{ cluster_type }}.yml"

- name: main | Stopping cluster Primary node
  command: pcs cluster stop
  when: ansible_hostname == node1 and cluster_type == 'hana'

- name: main | Stopping cluster Secondary node
  command: pcs cluster stop --force
  when: ansible_hostname == node2 and cluster_type == 'hana'

- name: main | hana-srhook
  include_tasks: hana-srhook.yml
  when: cluster_type == 'hana'

- name: main | Starting cluster 
  command: pcs cluster start 
  when: cluster_type == 'hana'