---
dry_run_vm:
  hosts:
    10.130.96.4:
ecc_dev:
  hosts:
    10.130.97.6:
ecc02_dev:
  hosts:
    10.130.97.8:
    10.130.97.10:
    10.130.97.12:
    10.130.97.16:
    10.130.97.18:
    10.130.97.20:
    10.130.97.22:
    10.130.97.24:
    10.130.97.26:
    10.130.97.28:
hcp_prod:
  hosts:
    10.130.1.82:
dummy_windows_vms:
  hosts:
    10.131.96.9
dummy_linux_vms:
  hosts:
    10.131.96.10
dummy_linux_vms_oxya:
  hosts:
    172.22.0.204
sandbox_dp_agent_oxya:
  hosts:
    172.22.9.154
sandbox_dp_agent_azure:
  hosts:
    10.130.98.134
open_text_canary:
  hosts:
    XECMSBXDB01.kherty.local:
sandbox_opentext:
  hosts:
    XECMSBXIDX01.kherty.local:
    XECMSBXARC01.kherty.local:
    XECMSBXDB02.kherty.local:
    XECMSBXDP01.kherty.local:
    XECMSBXFRT01.kherty.local:
    XECMSBXFRT02.kherty.local:
    XECMSBXDB01.kherty.local:
sandbox_opentextv2:
  hosts:
    XECMSBXARC01.kherty.local:
    XECMSBXDP01.kherty.local:
windows_tosca_dev:
  hosts:
    CASTDEVASA01.kherty.local:
    CASTDEVASA02.kherty.local:
    DEXDEVASA01.kherty.local:
    DEXDEVASA02.kherty.local:
    DEXDEVASA03.kherty.local:
    DEXDEVASA04.kherty.local:
    #PERF4ECUBE01.kherty.local:
    #PERF4ECUBE02.kherty.local:
windows_tosca_dev2:
  hosts:
    PERF4ECUBE01.kherty.local:
    PERF4ECUBE02.kherty.local:
windows_tosca_dev3:
  hosts:
    DEXDEVASA04.kherty.local:
windows_neva_nonprod:
  hosts:
    FRHQSV953.kherty.local:
    FRHQSV954.kherty.local:
    FRHQSV955.kherty.local:
    FRHQSV956.kherty.local:
    FRHQSV957.kherty.local:
windows_neva_nonprod_v2:
  hosts:
    EUR1026.vinci-construction.net:
windows_neva_nonprod_ip:
  hosts:
    10.131.128.30:
windows_xproxy_nonprod:
  hosts:
    INTE72.vinci-construction.net:
windows_xproxy_nonprod_ip:
  hosts:
    10.131.128.22:
windows_ilmt_prod:
  hosts:
    ITMANAGMIG.kherty.local:
windows_opentext_dev:
  hosts:
    XECMDEVARC01.kherty.local:
    XECMDEVDB01.kherty.local:
    XECMDEVDB02.kherty.local:
    XECMDEVDP01.kherty.local:
    XECMDEVFRT01.kherty.local:
    XECMDEVFRT02.kherty.local:
    XECMDEVIDX01.kherty.local:
windows_edayreport_dev:
  hosts:
    PAPYDEV02:
windows_papyrus_dev:
  hosts:
    PAPYDEV01:
windows_bsi_dev:
  hosts:
    PROCDIRDEV.kherty.local:
linux_axway_dev:
  hosts:
    SAPDEVDB12.kherty.local:
windows_webcycle_dev:
  hosts:
    KFXDEVASA01.kherty.local:
    PROCDIRDEV02.kherty.local:
windows_dsap_dev:
  hosts:
    FRHQSV1022.kherty.local:
linux_hip_dev:
  hosts:
    HIPDEVAS01:
    HIPDEVAS02:
linux_hip_dev2:
  hosts:
    HIPDEVAS03:
windows_hip_dev:
  hosts:
    HIPDEVDB01.kherty.local:
linux_dpagent_dev:
  hosts:
    SAPDPDAGT01:
windows_etreasury_dev:
  hosts:
    FSSDEV01:
windows_edayreport_dev_ip:
  hosts:
    #PAPYDEV02:
    10.131.128.38:
windows_papyrus_dev_ip:
  hosts:
    #PAPYDEV01:
    10.131.128.54:
linux_hip_dev_ip:
  hosts:
    #HIPDEVAS01:
    10.131.96.41:
    #HIPDEVAS02:
    10.131.96.38:
linux_hip_dev2_ip:
  hosts:
    #HIPDEVAS03:
    10.131.96.40:
linux_dpagent_dev_ip:
  hosts:
    #SAPDPDAGT01:
    10.130.98.150:
windows_etreasury_dev_ip:
  hosts:
    #FSSDEV01:
    10.130.128.22:
linux_appdebadge_prod:
  hosts:
    VBADGES-ETF:
windows_vplanning_prod:
  hosts:
    EUR1002:
windows_vplanning2_prod:
  hosts:
    FREF92-001SV111.kherty.local:
windows_navori_prod:
  hosts:
    FRHQSV1012.kherty.local:
linux_appdebadge_prod_ip:
  hosts:
    #VBADGES-ETF

windows_vplanning_prod_ip:
  hosts:
    #EUR1002
    172.26.6.2:
windows_vplanning2_prod_ip:
  hosts:
    #FREF92-001SV111.kherty.local
    172.26.0.43:
windows_navori_prod_ip:
  hosts:
    #FRHQSV1012.kherty.local
    172.22.0.191:
ecc_uat:
  hosts:
    #Q01
    10.130.65.8:
    #I03
    10.130.65.4:
    10.130.65.6:
    #WDU
    10.130.65.10: