- name: resource create fs_{{ sap.sid|upper }}_{{ sap.ascs_type }} 
  command: pcs resource create fs_{{ sap.sid|upper }}_{{ sap.ascs_type }} Filesystem device='{{ ascs_device }}' directory='/usr/sap/{{ sap.sid|upper }}/{{ sap.ascs_type }}{{ sap.instance_numbers.ascs }}' fstype='nfs' force_unmount=safe options='sec=sys,vers=4.1' op start interval=0 timeout=60 op stop interval=0 timeout=120 op monitor interval=200 timeout=40 --group g-{{ sap.sid|upper }}_{{ sap.ascs_type }}
  register: result
  failed_when: 
    - result.failed
    - not (result.stderr.find("already exists")) 

- name: resource create fs_{{ sap.sid|upper }}_ERS 
  command: pcs resource create fs_{{ sap.sid|upper }}_ERS Filesystem device='{{ ers_device }}' directory='/usr/sap/{{ sap.sid|upper }}/ERS{{ sap.instance_numbers.ers }}' fstype='nfs' force_unmount=safe options='sec=sys,vers=4.1' op start interval=0 timeout=60 op stop interval=0 timeout=120 op monitor interval=200 timeout=40 --group g-{{ sap.sid|upper }}_ERS
  register: result
  failed_when: 
    - result.failed
    - not (result.stderr.find("already exists")) 

- name: resource create vip_{{ sap.sid|upper }}_{{ sap.ascs_type }} 
  command: pcs resource create vip_{{ sap.sid|upper }}_{{ sap.ascs_type }} IPaddr2 ip={{ sap.logical_hosts.ascs.ip }} cidr_netmask={{ sap.logical_hosts.ascs.cidr }} --group g-{{ sap.sid|upper }}_{{ sap.ascs_type }}
  register: result
  failed_when: 
    - result.failed
    - not (result.stderr.find("already exists")) 

- name: resource create vip_{{ sap.sid|upper }}_ERS 
  command: pcs resource create vip_{{ sap.sid|upper }}_ERS IPaddr2 ip={{ sap.logical_hosts.ers.ip }} cidr_netmask={{ sap.logical_hosts.ers.cidr }} --group g-{{ sap.sid|upper }}_ERS
  register: result
  failed_when: 
    - result.failed
    - not (result.stderr.find("already exists")) 

- name: resource create nc_{{ sap.sid|upper }}_{{ sap.ascs_type }} 
  command: pcs resource create nc_{{ sap.sid|upper }}_{{ sap.ascs_type }} azure-lb port=620{{ sap.instance_numbers.ascs }} --group g-{{ sap.sid|upper }}_{{ sap.ascs_type }}
  register: result
  failed_when: 
    - result.failed
    - not (result.stderr.find("already exists")) 

- name: resource create nc_{{ sap.sid|upper }}_ERS 
  command: pcs resource create nc_{{ sap.sid|upper }}_ERS azure-lb port=621{{ sap.instance_numbers.ers }} --group g-{{ sap.sid|upper }}_ERS
  register: result
  failed_when: 
    - result.failed
    - not (result.stderr.find("already exists")) 