

# - name: Execute sql queries
#   win_command: sqlcmd -S {{ sql_db_host }} -U {{ sql_db_username }} -P {{ sql_db_password }} -Q "SELECT @@VERSION"
#   register: output

# - debug: var=output

- name: "Execut custom module on MSSQL"
  mssql_query:
   login_host: "{{ sql_db_host }}"
   port: "{{ sql_db_port }}"
   login_user: "{{ sql_db_username }}"
   login_password: "{{ sql_db_password }}"
   query: "{{ item.query }}"
   db: "{{ sql_db_name }}"
   autocommit: true
   tds_version: 7.1
   as_dict: true
  with_items: "{{ sql_queries }}"
  register: as_dict

- debug: var=as_dict
  
- name: Write ouptut
  copy:
      content: "{{ as_dict.results[index].result }}"
      dest: '{{ db_export_path }}{{ db_type }}/{{ item.name }}_output.json'
  with_items:
      - "{{ sql_queries }}"
  loop_control:
       index_var: index


