---
# defaults file for oel

# Define what sections to run
oelcis_01_initial: true
oelcis_02_services: true
oelcis_03_network: true
oelcis_04_logging: true
oelcis_05_access: true
oelcis_06_system: true

# Set to true to run either level1, level2, or set both to true to run level1 and level2 checks.
oelcis_level1: true
oelcis_level2: false

############################
### 01_initial Parameters ###
############################

# Section Partition #

# Section AIDE #

# Ensure AIDE is installed and configured
oelcis_config_aide: true

# SELinux Section #

# Ensure SELinux state is enforcing and configured
# true = SELinux is disabled | false = SELinux is enabled
oelcis_selinux_disable: false

# SELinux policy
oelcis_selinux_pol: targeted

cis_oel_min_uid: 1000
cis_oel_sudo_logfile: /var/log/sudo.log
cis_oel_priv_partitions:
  - /

# System package updates #

# Ensure updates of software repos and system packages are up-to-date | Run yum update
oelcis_update: true

# # Warning Banner Content (issue, issue.net, motd)
# oelcis_warning_banner: |
#     Authorized uses only. All activity may be monitored and reported.

# End Banner

############################
### 02_services Parameters ###
############################
# Set this to false to prevent disabling of services.
# Value of true will disable all services not excluded or skipped using the var booleans below.
# The disable_service_checks can also be enabled via the skip tag function by skipping "disable_service_checks" tag to the running playbook
oelcis_disable_service_checks: true

# Set this value to true if the machine is joined to AD/LDAP server.
# Set this value to false if the machine is not joined to AD/LDAP server.
oelcis_ad_ldap_joined_machine: true

# Service configuration booleans set true to keep service
oelcis_dhcp_server: false
oelcis_ldap_server: false
oelcis_telnet_server: false
oelcis_tftp_server: false
oelcis_rsh_server: false
oelcis_nis_server: false
oelcis_snmp_server: false
oelcis_httpd_server: false
oelcis_vsftpd_server: false
oelcis_named_server: false
oelcis_nfs_rpc_server: false
oelcis_vsftpd: false
oelcis_httpd: false

oelcis_telnet_required: false

# Ensure avahi server is not enabled
oelcis_avahi_server: false


############################
### 04_logging Parameters ###
############################

# Enable auditd
oelcis_enable_auditd: false

############################
### 05_access Parameters ###
############################

# Ensure at/cron is restricted to authorized users
oelcis_cron_allow_apply_template: false

# Section 5.3.1 | Ensure password creation requirements are configured
oelcis_password_creation_requirements: true

# Section 5.4.4 | Ensure default user umask is 027 or more restrictive
oelcis_modify_default_user_umask: true
oelcis_default_user_umask: 027

############################
### 06_system Parameters ###
############################

# Section 6.2.14 | Ensure no users have .rhosts files
oelcis_modify_dot_rhosts_files: false