- name: cluster | stop hana
  command: "{{ item }}"
  loop:
    - su - {{ sap.db.sid|lower }}adm -c "sapcontrol -nr {{ sap.instance_numbers.db }} -function StopWait 600 10"
    - sleep 20
  when: ansible_hostname == node2