---
- name: Create /etc/sysctl.d/sap.conf
  blockinfile:
    path: /etc/sysctl.d/sap.conf
    marker: "# {mark} ANF Configuration"
    create: yes
    block: |
      vm.max_map_count = 2147483647
      kernel.pid_max = 4194304
      vm.max_map_count = 2147483647
      kernel.sem = 32000 1024000000 500 32000
  when: ansible_distribution_major_version >= '8'


- name: main | tweak sysctl entries
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - { name: net.core.somaxconn, value: 4096 }
    - { name: net.ipv4.tcp_max_syn_backlog, value: 8192 }
    - { name: net.ipv4.tcp_slow_start_after_idle, value: 0 }
    - { name: net.ipv4.tcp_wmem, value: 4096 16384 4194304 }
    - { name: net.core.wmem_max , value: 212992 }
  when: ansible_distribution_major_version >= '8'

- name: main | tweak sysctl entries
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - { name: net.ipv4.tcp_tw_reuse , value: 1 }
  when: ansible_distribution_major_version >= '8' and hana_scale_out is defined